directory:
  submit: ./Submit                     
  output: ./Output                     
  done: ./Done                         
  error: ./ERROR                       
  src_path: ./src                      
  pot_path_gga: ./pot/PBE
  pot_path_lda: ./pot/LDA

program:
  vasp_std: ./vasp_std     
  vasp_gam: ./vasp_gam     
  vasp_ncl: ./vasp_ncl     
  gnuplot: /usr/local/bin/gnuplot                    
  mpi_command: mpirun                  

vasp_parallel:
  npar: 2                              
  kpar: 2

